#!/bin/bash

set -e

# Clone the lake
git clone https://github.com/CloudCannon/great-lakes-data.git

node great-lakes-data/format-collection.cjs blog

node great-lakes-data/format-data-file.cjs profiles

rm -rf great-lakes-data

# Update color variables to match variables data file
npm run prebuild:fetch-theme-color